
services:
  api:
    container_name: pula_api
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env  
    networks:
      - docker-network
    depends_on:
      - postgres 

  postgres:
    container_name: pula_db
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_USER: ${DB_USERNAME}  
      POSTGRES_DB: ${DB_NAME}  
    ports:
      - "${DB_PORT}:${DB_PORT}"  
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - docker-network

networks:
  docker-network:

volumes:
  postgres_data:
